# Generated by Django 5.1.3 on 2024-12-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_payment_payment_link_payment_session_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_status",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="статус оплаты"
            ),
        ),
    ]
